### ISSUE TITLE
Problems linking with Chase - Plaid opens Chase app which opens a Universal Link in the browser instead

### ISSUE THREAD

**Issue by Crizzooo** [plaid/react-native-plaid-link-sdk#302]
# The problem

On iOS, when Chase app is installed, plaid link appears to open the Chase app. This is not the same flow with many other banks, such as BofA, that handle the whole flow in the plaid link window.

The issue is that after completing the Chase flow, the redirect URI is opened in the browser context. We see "plaid.cdn" in the top, which eventually follows the link and ends up on an app store download page. The end result is that the app is completely unaware of what took place in the Chase app, and asks the user to continue to sign in to Chase.

Is this a problem with Chase, our config, or with Plaid link?

Is this redirectURI being evaluated in a web context? 

Clicking the URL directly on iOS/Slack/Text correctly opens the app, but pasting it in Safari has the same behavior as the Chase flow -> goes to an app store download.

I dont think this is a problem with the universal link.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | e.g. 6.0.2                |
| ReactNative Version     | e.g. 0.61.3                |
| Occurs on Android             | e.g. no                |
| Occurs on iOS     | e.g. yes                |
| iOS Version           | e.g. 11                |
| iOS Devices/Emulators               | e.g. iPhone X                |

# Steps to Reproduce

If necessary, describe the problem you have been experiencing in more detail.
Please include the configuration you are using for Link (excluding your keys
and personally identifiable information)

1. Configure Plaid Link OAuth, verify it works with Platypus test bank
2. Try linking process on an iOS device, with the Chase App installed.

# Expected Result
What did you expect to happen?

Successful redirect back to the app, from the Chase app.

# Screenshots

Cant share video as it includes partial Account numbers.

Im more so looking for any guidance, suggestions or knowledge to debug this. Just a pointer in the right direction.

**Comment by Crizzooo** [comment]
This might actually be the same issue I just found here:

https://github.com/plaid/react-native-plaid-link-sdk/issues/257

Will try updating to 6.0.3 and report back

**Comment by Crizzooo** [comment]
6.0.3 and implementing RCTLinkManager instead of our BranchManager, has fixed the problem.

**However**, the user's default browser must be Safari. If it's Chrome, our link is not redirecting back to the app, but to an app store.

Any ideas on the difference between how Safari and Chrome are treating these redirect URIs?

**Comment by Crizzooo** [comment]
When using Chrome to link a bank, iOS does not process the redirect with the `RCTLinkingManager` restorationHandler.

The app is successfully given focus, but the plaid-link component is not aware.

We are using Branch, and when the Universal Link fails, we end up on a Branch deep view. This redirect fails to communicate back to Plaid Link when the app activity is restored.

I do have the `oauthStateId` prop in that redirect. How can I use this to advance the plaid link state?

**Comment by pladaub** [comment]
We'll investigate the default browser behaviour difference and report back. Thank you for your patience!

**Comment by IljaDaderko** [comment]
Same issue happens when using firebase dynamic links. User can authenticate correctly and gets back to the app, however plaid remains on "Continue to sign in" screen asking to authenticate with a bank. This is European flow as well and happens in v7

**Comment by Crizzooo** [comment]
Any update on this?

**Comment by pladaub** [comment]
We're continuing to investigate internally, but haven't found a workaround yet. Once we've found one, I'll update the ticket with projected timelines for release as well as information about where the workaround lives (it's possible it can be done on our side without any required SDK changes) and therefore required next steps for integrators.

Thanks for your patience!

**Comment by pladaub** [comment]
We identified the issue early this week, and yesterday pushed a fix to production. The workaround was able to be implemented on our side, and so no further action is required by clients.

Thanks so much for flagging this!

**Comment by fernandatoledo** [comment]
@pladaub was this solved for every browser or just chrome? I am still having the issue using DuckDuckGo,

**Comment by pladaub** [comment]
This was solved using a browser allowlist, we will add DuckDuckGo to our allow list. It may take a day or two for the change to propagate, but it will not require any further action

**Comment by fernandatoledo** [comment]
Thank you! I don't really understand how works internally but, instead of having a list of allowed browsers can't it be checked against just safari, because it will have this new behavior for all the remaining ones, on iOS. 

Works for chrome and firefox perfectly, but still not working for duckduckgo, brave, and there are many other browsers that are gaining popularity every day

**Comment by pladaub** [comment]
In order to just detect Safari we would have to parse the user-agent more exhaustively as the user-agents for Safari and other browsers (e.g. Chrome/Firefox) are quite similar. The concern is that this parsing will be more brittle, and therefore impact more user traffic, than the allowlist approach.

Unfortunately, some browsers (Brave) do not have a unique user agent at all, so we can't support them without degrading support for all sessions. We'll look into collecting more data to see which approach has the best result in terms of conversion weighted by user traffic.

With regards to DuckDuckGo specifically, the allowlist deploy has not been pushed yet. I will update the ticket when it is, and I apologize for the delay. It also appears as though DuckDuckGo has stopped reporting a consistent user-agent as of iOS 14.5. I'll investigate this more

**Comment by Crizzooo** [comment]
Getting reports of this again on iOS with Safari + Chase App.

Have yall recently changed anything since initially pushing your fix on April 14? It appeared to be working after that. @pladaub

**Comment by meshuamam** [comment]
@pladaub can you please also add Brave browser to the allow list?

**Comment by thamizhbharathi** [comment]
Plaid sandbox is working fine only for chase bank in IOS, but not for other banks 
@pladaub Can you please help me to sort this out?

Note: I am using react native , and in android other banks like bank of america, citi bank, capital one all are working fine

**Comment by phoenixy1** [comment]
@thamizhbharathi This issue was closed over 3 years ago. If you're having a problem, please open a new issue and fully complete the issue template.
