### ISSUE TITLE
App is crashing on clicking on continue button on  success plaid screen

### ISSUE THREAD

**Issue by mountainfirefly** [plaid/react-native-plaid-link-sdk#343]
# The problem

I just updated react-native-plaid-link-sdk to v7.0.0 and the app is crashing on clicking on the continue button on the success plaid screen.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | v7.0.0                |
| ReactNative Version     | v0.63.2                |
| iOS Devices/Emulators               | iPhone 12               |
| Plaid               | v2.0.11             |

# Steps to Reproduce
- Enter user details and click next.
- Account gets linked successfully.
- Click on the continue button and the app crashes.

# Error

Getting this error on the Xcode console output.
```
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003475e50 UIButtonLabel:0x7fcbca8c7860.centerY == _UIModernBarButton:0x7fcbca8c5a30'Done'.centerY + 1.5   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-03-17 18:54:01.349480+0530 Line[47888:320060] -[PLKSuccessMetadata institution]: unrecognized selector sent to instance 0x6000018a5d40
2021-03-17 18:54:01.360846+0530 Line[47888:320060] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PLKSuccessMetadata institution]: unrecognized selector sent to instance 0x6000018a5d40'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204306f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff20426036 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20428068 _CF_forwarding_prep_0 + 120
	5   Line                                0x000000010376731c +[RNLinksdk dictionaryFromSuccess:] + 428
	6   Line                                0x0000000103762b07 __20-[RNLinksdk create:]_block_invoke + 263
	7   LinkKit                             0x000000010f2ebc1c block_destroy_helper.8 + 19468
	8   LinkKit                             0x000000010f2dc915 globalinit_33_3539F515EB857A77839ECAB662545DDA_func120 + 12181
	9   LinkKit                             0x000000010f2acbde __swift_project_boxed_opaque_existential_1 + 3118
	10  libdispatch.dylib                   0x000000010fecc7ec _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000010fecd9c8 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010fedbe75 _dispatch_main_queue_callback_4CF + 1152
	13  CoreFoundation                      0x00007fff2038fdbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x00007fff2038a63e __CFRunLoopRun + 2685
	15  CoreFoundation                      0x00007fff203896d6 CFRunLoopRunSpecific + 567
	16  GraphicsServices                    0x00007fff2c257db3 GSEventRunModal + 139
	17  UIKitCore                           0x00007fff24696cf7 -[UIApplication _run] + 912
	18  UIKitCore                           0x00007fff2469bba8 UIApplicationMain + 101
	19  Line                                0x0000000102ef59b0 main + 112
	20  libdyld.dylib                       0x00007fff2025a3e9 start + 1
	21  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PLKSuccessMetadata institution]: unrecognized selector sent to instance 0x6000018a5d40'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 (B681C767-9B56-40BA-9BFC-A46D022E610D) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12
```

<details><summary>Screenshot of success screen</summary>
<img width=50% src='https://user-images.githubusercontent.com/11595211/111476892-9616a080-8754-11eb-8f02-11835a07631d.png'>
</details>

**Comment by afh** [comment]
Thank you for your report @mountainfirefly, we're looking into it.

**Comment by afh** [comment]
@mountainfirefly we will need more information from you to investigate as we are unable to reproduce the crash you are observing.

* What are the parameters you are using to generate the link token?
* Which institution did you select?
* Does the crash occur with any institution?

**Comment by mountainfirefly** [comment]
@afh We are facing this with all the institutions and it works fine with the previous versions of Plaid.

I have attached a video of a crash, please have a look and let me know if you need anything else.


https://user-images.githubusercontent.com/11595211/111580316-52b44480-87dd-11eb-9b57-dbf4415558d3.mov

**Comment by afh** [comment]
@mountainfirefly Thank you for following up on with a video.

Link tokens are an integral part and determine which Link flow is run, and in order for us to be able to investigate further please follow up with the parameters you are sending to the `/link/token/create` endpoint (with sensitive information including but not limited to `client-id`, `secret`, etc. redacted) to create a Link token. Or are you still using a public key based integration? In which case we recommend to [migrate to Link tokens](https://plaid.com/docs/link/link-token-migration-guide/).

**Comment by mountainfirefly** [comment]
@afh 

Plaid Link Token: `link-sandbox-ec5eea77-284a-49de-b60d-a67879e52028`

Plaid token generation params
```
{
    user: {
      client_user_id: "5f9f0320e818901e7d9bxxxx",
    },
    client_name: "Company Name",
    products: ["auth", "transactions"],
    country_codes: ["US"],
    language: "en",
    webhook: "https://webhookUrl",
  }
```

Let me know if you are required anything else.

**Comment by afh** [comment]
Quick check @mountainfirefly :

The `user.client_user_id` you provided looks rather similar to aPlaid API [`client_id`](https://plaid.com/docs/api/tokens/#link-token-create-request-client-id) can you verify it is **not** and confirm that it is indeed _"[a] unique ID representing the end user. Typically this will be a user ID number from your application"_ (see[Plaid Documentation Token endpoints](https://plaid.com/docs/api/tokens/#link-token-create-request-client-user-id)).

**Comment by afh** [comment]
@mountainfirefly Using the Link Token you provided earlier I was able to complete the Plaid Link flow successfully using the [React-Native example](https://github.com/plaid/react-native-plaid-link-sdk/tree/master/example) 

Can you reproduce the crash with the [React-Native example](https://github.com/plaid/react-native-plaid-link-sdk/tree/master/example) ?

**Comment by craj** [comment]
@afh I'm from @mountainfirefly's backend team. Yes, the `client_user_id` is the unique userId associated with the user on our platform and not the plaid client Id. We'll check for the issue with RN example app and why it's failing at our end and get back to you.

**Comment by afh** [comment]
Thanks for the update @craj, we continue with the investigation on our end too.

**Comment by mountainfirefly** [comment]
Hey @afh,

Sorry for the late response, we were on holidays.

I wasn't able to replicate this crash with `react-native example`, it is working fine. But with our it is crashing, I am sure there is something wrong with our app.

I found one thing, commenting out 513 in `RNLinksdk.m` the doesn't crash the app.
<img width="1298" alt="Screenshot 2021-03-30 at 8 57 40 AM" src="https://user-images.githubusercontent.com/11595211/112929920-03540980-9137-11eb-8af7-e9816de9f77e.png">

This is the error we get in the Xcode console.
```
NSInvalidArgumentException', reason: '-[PLKSuccessMetadata institution]: unrecognized selector sent to instance 0x6000018a5d40'
terminating with uncaught exception of type NSException
``` 
I am not familiar with swift, can you please tell me why this could be coming up?

**Comment by afh** [comment]
Hmm 🤔, I wonder whether there's a translation issue in the Swift / Objective-C bridge… Can you set a breakpoint on 509 and:
```
lldb> po success
lldb> po succcess.metadata
lldb> po [succcess.metadata class]
```

and send over the what is printed in the Xcode console please?

**Comment by mountainfirefly** [comment]
Yes,
Here it is
<img width="1440" alt="Screenshot 2021-03-31 at 10 49 45 AM" src="https://user-images.githubusercontent.com/11595211/113095440-0cb1a480-9211-11eb-8550-105c8f185557.png">

**Comment by afh** [comment]
Thanks for your response @mountainfirefly, in addition to screenshots sharing information in text makes it much easier to inspect.

It seems seems my initial request has a typo in :/ Mind running it again:
```
lldb> po success.metadata
lldb> po [success.metadata class]
```

**Comment by mountainfirefly** [comment]
Yes sure, here it is. @afh 
<img width="1440" alt="Screenshot 2021-04-02 at 5 54 16 PM" src="https://user-images.githubusercontent.com/11595211/113415695-64047000-93dd-11eb-920e-06522b996027.png">

**Comment by afh** [comment]
Thanks @mountainfirefly, once I again I'd like to emphasize that in addition to screenshots sharing textual data is very helpful for us.

Unfortunately there is a typo in the Plaid Link Objective-C bridge that interfaces with React Native for Plaid Link version < 2.0.11.
It defines a `insitution` (instead of `institution`) property on the `PLKSuccessMetadata`, hence
the code accessing `metadata.institution` crashes as such a property does not exist.
<details><summary>Annotated Screenshot</summary>

![](https://user-images.githubusercontent.com/16507/113687263-6eb65200-96c8-11eb-9798-a0bb8f3f3d63.png)

</details>

This has been addressed with version [2.0.11](https://github.com/plaid/plaid-link-ios/releases/tag/ios%2F2.0.11), can you double check that version 2.0.11 is really used in your project by cleaning the build folder (**Xcode ❯ Project ❯ Clean Build Folder ⇧ ⌘ K**) and rebuilding.

**Comment by pladaub** [comment]
Chiming in here:

Internally we noticed that in some circumstances `2.0.11` does appear to be used, but the fix for the typo does not appear to be in place. Our best theory is that something is acting up with Cocoapods, and the reported version is inaccurate.

In order to see if the fix is in place, could you:

`po [success.metadata institution]`

And 
`po [success.metadata insitution]`

One, but never both, should be a valid selector. If `-[PLKSuccessMetadata insitution]` is valid, the linked version is pre iOS `2.0.11`. If `[success.metadata institution]` is valid then the version is `2.0.11` or newer.

**Comment by mountainfirefly** [comment]
Hey, @afh I have cleaned the project and build it again but still getting the same error.

I guess the fix is not in place, tried commands given by @pladaub 

<img width="1137" alt="Screenshot 2021-04-10 at 11 06 32 AM" src="https://user-images.githubusercontent.com/11595211/114259665-35922080-99ed-11eb-9a3d-9dadb4356c97.png">

**Comment by afh** [comment]
Sorry to hear that you are still experiencing the issue, @mountainfirefly.

I verified that the fix is indeed included in 2.0.11, could it be a caching issue with the dependency management?
* Which version of CocoaPods are you using (`pod --version`)?
* Which Plaid related entries are in your `Podfile` and `Podfile.lock`?
* How does your `package.json` look like?
* How did you ensure that Link version `2.0.11` is used 
* Which version is included in the LinkKit.framework's Info.plist (note, that the path to the Info.plist depends on your development setup and `pwd`), e.g.:
```
% /usr/libexec/PlistBuddy \
  -c 'Print CFBundleShortVersionString' \
  -c 'Print SCMBuildRevision' \
  -c 'Print SCMBuildBranch' \
  -c 'Print SCMBuildNumber' \
  ios/Pods/Plaid/LinkKit.xcframework/ios-arm64/LinkKit.framework/Info.plist
```

A possible workaround for the time being would include changing `metadata.institution` to `metadata.insitution` in `RNLinksdk.m:514`, yet that workaround would need to be reverted

**Comment by afh** [comment]
Any update on this @mountainfirefly?

**Comment by mountainfirefly** [comment]
@afh I went ahead with the workaround for now.
 
 I am sure there is caching issue at our end, but I have tried everything to clear the cache but the issue still persists.
 We will wait for the new version for plaid, let see it gets fixed in that.
 
 Thank you so much for your help.

**Comment by afh** [comment]
Thanks for your response @mountainfirefly.
The steps mentioned in [this previous comment](https://github.com/plaid/react-native-plaid-link-sdk/issues/343#issuecomment-817727978) should help determining where a potential caching issue may lie, should you want to take further action until the next version of the Plaid Link for iOS SDK is released.

**Comment by envisean** [comment]
@pladaub we are also having this issue, and no matter what we do: reinstall pods, clearing cache, etc., it seems that it will constantly revert back to using a version that has the typo.
