### ISSUE TITLE
React Native Plaid SDK 12 is not compatible with React Native 0.76

### ISSUE THREAD

**Issue by suresh-ignitershub** [plaid/react-native-plaid-link-sdk#742]
The current version of the React Native Plaid Link SDK (v12.x.x) is incompatible with React Native 0.76. When attempting to integrate the SDK, open() method to open plaid interface is not working and getting the error with using EmbeddedLinkView.

<img width="256" alt="Image" src="https://github.com/user-attachments/assets/9fc87e13-5221-409c-8a70-237d74438c7b" />

Steps to Reproduce:

- Set up a new React Native project with version 0.76:

`npx react-native init PlaidTest --version 0.76`

- Install React Native Plaid SDK 12:
`npm install react-native-plaid-link-sdk@12`

Attempt to run the project.
- Expected Behavior:
The React Native Plaid SDK 12 should work seamlessly with React Native 0.76.

- Actual Behavior:
The project fails to build or run due to incompatibility between the Plaid SDK and React Native 0.76. Specific errors include:

open() method is not opening the plaid interface and not giving any error.

Environment:
React Native Version: 0.76.x
React Native Plaid SDK Version: 12.x.x
Platform: IOS
Node.js Version: 20.x.x

**Comment by dtroupe-plaid** [comment]
Hi @suresh-ignitershub,

Could you provide more details on the issue you're facing? I tried running npx @react-native-community/cli@latest init PlaidTest to create a project using React Native 0.76.6, and when I run pod install, I encounter the following error:

```
UnsupportedFunctionParamTypeAnnotationParserError: Module NativePlaidLinkModuleiOS: Function parameter 'success' cannot have type 'VoidTypeAnnotation'.
    at throwIfUnsupportedFunctionParamTypeAnnotationParserError (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/error-utils.js:253:9)
    at /Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:442:16
    at guard (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/utils.js:31:14)
    at translateFunctionTypeAnnotation (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:418:25)
    at emitFunction (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-primitives.js:173:48)
    at translateTypeAnnotation (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:363:14)
    at /Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:424:11
    at guard (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/utils.js:31:14)
    at translateFunctionTypeAnnotation (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:418:25)
    at buildPropertySchema (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:535:7) {
  nodes: [
    Node {
      type: 'TSTypeAnnotation',
      start: 1012,
      end: 1018,
      loc: [SourceLocation],
      typeAnnotation: [Node]
    }
  ]
}
```

You mentioned that:

"The project fails to build"
"The open() method is not opening the Plaid interface and not giving any error."

If the project is failing to build, how are you able to call the open() method? Could you clarify whether the issue is during build or when executing the open() method? This will help in narrowing down the cause of the problem.

Looking forward to your response!

**Comment by zedelashvililevani** [comment]
If you want to pass, just should change

`NativePlaidLinkModuleiOS.ts -> syncFinanceKit -> onError: (error: FinanceKitError) => void
and 
onSuccess: (success: void) => void,`

**Android** build will be fixed, but on **IOS** we got:

`Undefined symbols for architecture x86_64
┌─ Symbol: _PLKEmbeddedViewCls
└─ Referenced from: _RCTThirdPartyFabricComponentsProvider in RCTFabric[x86_64][42](RCTThirdPartyFabricComponentsProvider.o)

❌  ld: symbol(s) not found for architecture x86_64`

**Comment by suresh-ignitershub** [comment]
@dtroupe-plaid @zedelashvililevani Thanks for your response!
I am capable of creating the iOS build by including the `pod 'Plaid', '~> 6.0.1'` in the Podfile. However, the Plaid interface does not open using the method described in the SDK, and no errors are reported. It appears that the event is not being triggered from the Plaid SDK with the latest React version 0.76, although it functions correctly with React version 0.73. We are currently seeking a workaround to ensure compatibility with the latest React version, as we prefer not to downgrade.

```
function createLinkOpenProps(): LinkOpenProps {
  return {
    onSuccess: (success: LinkSuccess) => {
      // User was able to successfully link their account.
      console.log('Success: ', success);
    },
    onExit: (linkExit: LinkExit) => {
      // User exited Link session. There may or may not be an error depending on what occured.
      console.log('Exit: ', linkExit);
      dismissLink();
    },
    // MODAL or FULL_SCREEEN presentation on iOS. Defaults to MODAL.
    iOSPresentationStyle: LinkIOSPresentationStyle.MODAL,
    logLevel: LinkLogLevel.ERROR,
  };
}

const openProps = createLinkOpenProps();
open(openProps);
```

**Comment by dtroupe-plaid** [comment]
@suresh-ignitershub are you calling [create](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/src/PlaidLink.tsx#L39) before `open`?

**Comment by suresh-ignitershub** [comment]
@dtroupe-plaid Yes, I am calling the 'create' function before the 'open' function. Below is the implemented code.
// Logic: Methods
`function createLinkTokenConfiguration(
    token: string,
    noLoadingState: boolean = false,
  ): LinkTokenConfiguration {
    return {
      token: token,
      // Hides native activity indicator if true.
      noLoadingState: noLoadingState,
    };
  }
  
  const tokenConfiguration = createLinkTokenConfiguration(linkToken);
  create(tokenConfiguration);

  function createLinkOpenProps(): LinkOpenProps {
    return {
      onSuccess: (success: LinkSuccess) => {
        // User was able to successfully link their account.
        console.log('Success: ', success);
      },
      onExit: (linkExit: LinkExit) => {
        // User exited Link session. There may or may not be an error depending on what occured.
        console.log('Exit: ', linkExit);
        dismissLink();
      },
      // MODAL or FULL_SCREEEN presentation on iOS. Defaults to MODAL.
      iOSPresentationStyle: LinkIOSPresentationStyle.FULL_SCREEN, // tried using MODAL as well but result is same
      logLevel: LinkLogLevel.ERROR,
    };
  }`

// Render: UI Definition
`<TouchableOpacity
            style={styles.continueButton}
            onPress={() => {
              console.log('Opening plaid link')
              const openProps = createLinkOpenProps();
              console.log('openProps-------', openProps)
              open(openProps);
            }}
            activeOpacity={0.7}
          >
            <Text style={styles.continueButtonText}>Continue to Plaid</Text>
          </TouchableOpacity>`

**Comment by Aya-Sato** [comment]
@dtroupe-plaid I am getting the same `UnsupportedFunctionParamTypeAnnotationParserError: Module NativePlaidLinkModuleiOS: Function parameter 'success' cannot have type 'VoidTypeAnnotation'.` error when trying to trigger an iOS build for an Expo project. 

Have you found a solution to resolve the error?

**Comment by dtroupe-plaid** [comment]
@Aya-Sato 

>when trying to trigger an iOS build for an Expo project

Currently Expo is not supported by this SDK.

**Comment by Aya-Sato** [comment]
> [@Aya-Sato](https://github.com/Aya-Sato)
> 
> > when trying to trigger an iOS build for an Expo project
> 
> Currently Expo is not supported by this SDK.

@dtroupe-plaid Thank you for your reply. I should have specified, I get the error when I eject from Expo into bare React Native and run `pod install`. So I think it is the same error as what you were getting?

**Comment by rameesp** [comment]
> Hi [@suresh-ignitershub](https://github.com/suresh-ignitershub),
> 
> Could you provide more details on the issue you're facing? I tried running npx @react-native-community/cli@latest init PlaidTest to create a project using React Native 0.76.6, and when I run pod install, I encounter the following error:
> 
> ```
> UnsupportedFunctionParamTypeAnnotationParserError: Module NativePlaidLinkModuleiOS: Function parameter 'success' cannot have type 'VoidTypeAnnotation'.
>     at throwIfUnsupportedFunctionParamTypeAnnotationParserError (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/error-utils.js:253:9)
>     at /Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:442:16
>     at guard (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/utils.js:31:14)
>     at translateFunctionTypeAnnotation (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:418:25)
>     at emitFunction (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-primitives.js:173:48)
>     at translateTypeAnnotation (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:363:14)
>     at /Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:424:11
>     at guard (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/utils.js:31:14)
>     at translateFunctionTypeAnnotation (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:418:25)
>     at buildPropertySchema (/Users/dtroupe/Desktop/PlaidTest/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:535:7) {
>   nodes: [
>     Node {
>       type: 'TSTypeAnnotation',
>       start: 1012,
>       end: 1018,
>       loc: [SourceLocation],
>       typeAnnotation: [Node]
>     }
>   ]
> }
> ```
> 
> You mentioned that:
> 
> "The project fails to build" "The open() method is not opening the Plaid interface and not giving any error."
> 
> If the project is failing to build, how are you able to call the open() method? Could you clarify whether the issue is during build or when executing the open() method? This will help in narrowing down the cause of the problem.
> 
> Looking forward to your response!

I fixed the build error by disabling codegen for Plaid by adding this code to the react-native-config.js file.
..................................
`  dependencies: {
    'react-native-plaid-link-sdk': {
      platforms: {
        ios: null, // Disable codegen for iOS
        android: null, // Disable codegen for Android (if applicable)
      },
    },
  },
`..................................

But plaid open() is not working now

**Comment by rameesp** [comment]
> The current version of the React Native Plaid Link SDK (v12.x.x) is incompatible with React Native 0.76. When attempting to integrate the SDK, open() method to open plaid interface is not working and getting the error with using EmbeddedLinkView.
> 
> <img alt="Image" width="256" src="https://private-user-images.githubusercontent.com/96281633/403056351-9fc87e13-5221-409c-8a70-237d74438c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0NDQ4NjcsIm5iZiI6MTczNzQ0NDU2NywicGF0aCI6Ii85NjI4MTYzMy80MDMwNTYzNTEtOWZjODdlMTMtNTIyMS00MDljLThhNzAtMjM3ZDc0NDM4YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIxVDA3MjkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOTVhZGIxMTg2YTJlYzI5YTJmZmQzMDIxMTVlZWUzZmNiZTExMjMwNjIxNDEwNTU2NGRmNTllMGYwOTg4OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a4kOYnZNyeZrfRuNpLZNMVziHu2D0P_yYOj8TmiZSQ0">
> Steps to Reproduce:
> 
> * Set up a new React Native project with version 0.76:
> 
> `npx react-native init PlaidTest --version 0.76`
> 
> * Install React Native Plaid SDK 12:
>   `npm install react-native-plaid-link-sdk@12`
> 
> Attempt to run the project.
> 
> * Expected Behavior:
>   The React Native Plaid SDK 12 should work seamlessly with React Native 0.76.
> * Actual Behavior:
>   The project fails to build or run due to incompatibility between the Plaid SDK and React Native 0.76. Specific errors include:
> 
> open() method is not opening the plaid interface and not giving any error.
> 
> Environment: React Native Version: 0.76.x React Native Plaid SDK Version: 12.x.x Platform: IOS Node.js Version: 20.x.x

`UnsupportedFunctionParamTypeAnnotationParserError: Module NativePlaidLinkModuleiOS: Function parameter 'success' cannot have type 'VoidTypeAnnotation'.`

**Comment by zedelashvililevani** [comment]
Yes it's basically RN-76 codegen compatibility problem on plaid SDK 12.
Waiting for the upgrade/fix  🙏

**Comment by doctorrokter** [comment]
Same issue for me during `pod install`:
`UnsupportedFunctionParamTypeAnnotationParserError: Module NativePlaidLinkModuleiOS: Function parameter 'success' cannot have type 'VoidTypeAnnotation'.
    at throwIfUnsupportedFunctionParamTypeAnnotationParserError (/Users/expo/workingdir/build/app/node_modules/@react-native/codegen/lib/parsers/error-utils.js:253:9)`

Tried multiple pods of Plaid for iOS: `6.0.0`, `6.0.1`, `6.0.2`. Doesn't help.
Android builds just fine, but untested the actual work of the SDK.

Will postpone upgrade to v12 until iOS is fixed. Staying on v11 for now.

React Native version is `0.76.6` (+ Expo 52)

**Comment by suresh-ignitershub** [comment]
We have attempted to resolve the issue using the latest SDK version 12.0.3; however, the same error persists. The open method for accessing the Plaid interface is unresponsive, and the embedded view is also experiencing the same error. Please refer to the attached recording for further details.

https://github.com/user-attachments/assets/75a3eb60-8398-4aee-b555-539a11b1c8e1

**Comment by suresh-ignitershub** [comment]
The issue has been resolved; it was traced back to a configuration error on our end that was causing the problem. we can close this ticket. Thanks!
